version: '3.5'

services:
  mariadb:
    image: mariadb:10.11.5
    command: mysqld --character-set-server=utf8 --collation-server=utf8_spanish_ci
    ports:
      - 3306:3306

    environment:
      - MYSQL_ROOT_PASSWORD=restauranteroot 
      - MYSQL_DATABASE=santjhoanedb
      - MYSQL_USER=restaurante
      - MYSQL_PASSWORD=restaurantepas

    volumes:
      - ~/dev/docker-volumes/santjhoane/database:/var/lib/mysql