version: '3.5'

services:
  mariadb:
    image: mariadb:10.11.5
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_spanish_ci
    ports:
      - 3306:3306

    environment:
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test

    volumes:
      - ~/dev/docker-volumes/hostelo/database:/var/lib/mysql