version: '3.5'

services:
  mariadb:
    image: mariadb:10.11.5
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_spanish_ci
    ports:
      - 3306:3306

    environment:
      - MYSQL_ROOT_PASSWORD=supersecretpassword 
      - MYSQL_DATABASE=databasename
      - MYSQL_USER=username
      - MYSQL_PASSWORD=supersecretpassword

    volumes:
      - ~/dev/docker-volumes/database:/var/lib/mysql